# Generated by Django 4.2.6 on 2023-11-23 09:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_p_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCaraousel',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('hc_title', models.CharField(max_length=255)),
                ('hc_description', models.TextField()),
                ('hc_image', models.ImageField(upload_to='home_carousel_images')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
