# Generated by Django 4.2.6 on 2023-11-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_homecaraousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='c_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images'),
        ),
    ]
