# Generated by Django 4.2.6 on 2023-11-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_category_c_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='c_buy_count',
            field=models.IntegerField(default=0),
        ),
    ]
