# Generated by Django 4.2.6 on 2023-11-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_discount_product_p_buy_count_product_p_mrp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
