# Generated by Django 4.2.6 on 2023-11-23 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_product_p_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.discount'),
        ),
    ]
