# Generated by Django 4.2.7 on 2023-12-28 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_cart_cartitems'),
        ('shop', '0011_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='r_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
